env:
  browser: true
  es6: true
  jquery: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - tab
  quotes:
    - error
    - double
  semi:
    - error
    - always
  spaced-comment:
    - always
