env:
  browser: true
  es6: true
  jquery: true
extends: eslint:recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - tab
  quotes:
    - error
    - double
  semi:
    - error
    - always
  space-before-function-paren:
    - error
    - never
  spaced-comment:
    - 1
  no-console: off
  no-tabs: off
  eqeqeq: off
