# deal with it.. or not, i guess
preprocess_command: "sed '1{/^---$/{:a N;/---$/!ba;d}}'"

rules:
  indentation:
    - 0
    - size: tab
  quotes:
    - 1
    - style: double
  no-css-comments: 
    - 0
  hex-notation: 
    - 1
    - style: uppercase
  no-color-literals:
    - 0
  single-line-per-selector:
    - 0
  no-color-keywords:
    - 0
  nesting-depth:
    - max_depth: 3
