# Site settings
title: Start9
description: > # this means to ignore newlines until "baseurl:"
An extensible, customizable, modular shell supplement for Windows.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://startnine.github.io" # the base hostname & protocol for your site
github_username:  startnine

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
