# Site settings
title: Start9
description: An extensible, customizable, modular shell supplement for Windows.
url: "https://start9.menu/" # the base hostname & protocol for your site
github_username: startnine

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
sass:
  sass_dir: assets
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
